services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/pifsm
    environment:
      - FLASK_DEBUG=1
    command: flask run -h 0.0.0.0
  db:
    image: postgres
    environment:
      POSTGRES_USERl: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    ports:
     - 8080:8080